import Nav from '@/components/Nav';

export const metadata = {
  title: '  Web flow',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <main>
        <Nav />
        {children}
      </main> */}
      <html lang="en">
        <body>
          <div className="main">
            <div className="gradient" />
          </div>

          <main className="app">
            <Nav />
            {children}
          </main>
        </body>
      </html>
    </html>
  );
}
